# Что за Workflow
name: Build

# Когда он запускается
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Позволяет вручную запускать Workflow
  workflow_dispatch:

jobs:
  setup_and_build:
    # Контейнер, в котором запускается задание
    runs-on: ubuntu-latest

    # Шаги задания
    steps:
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # What compiler do we have?
      - name: Run build for prog1
        run:  echo cс --version

      # Runs build using the runners shell
      - name: Собираем программу
        run: |
          cd prog1
          cc main.c

      - name: env
        run: env

  test:
    # Зависимости
    needs:
      - setup_and_build

    # Контейнер, в котором запускается задание
    runs-on: ubuntu-latest

    # Шаги задания
    steps:
      - run: |
          echo Пока делать нечего
